# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160205_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='betaald',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='naam',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='regid',
            field=models.TextField(null=True),
        ),
    ]
